exchaD_win10/Models/ErrorViewModel.cs
using System;

namespace exchaD.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

exchaD_win10/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace exchaD_win10.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DefaultController : ControllerBase
    {
        // GET: api/Default
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Default/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Default
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT: api/Default/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

exchaD_win10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using exchaD.Models;

namespace exchaD.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

exchaD_win10/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using exchaD.Data;

namespace exchaD.Controllers
{
	//ログアウト処理を担う
    public class LogoutController : Controller
    {
		//メンバ
		private readonly ExchaDContext5 _context;

		//コンストラクタ
		public LogoutController(ExchaDContext5 context)
		{
			_context = context;
		}

		//デフォルトのアクション
		public IActionResult Index()
		{
			return Redirect("/");
		}
	}
}

exchaD_win10/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;    //DbSet.ToListAsync()
using Microsoft.AspNetCore.Authentication;	//login


using exchaD.Data;

namespace exchaD.Controllers
{
	//ページ表示処理を担う
    public class PagesController : Controller
    {
		//メンバ
		private readonly ExchaDContext5 context;
		
		//コンストラクタ
		public PagesController(ExchaDContext5 c)
		{
			context = c;
		}

		//デフォルトのアクション----------------------------------------
		public IActionResult Index()
		{
			return View("~/Views/Pages/top.cshtml");
		}
		//日記一覧の表示---------------------------------------------------------------
		public async Task<IActionResult> diaries()
		{
			return View(await context.diaries.ToListAsync());
		}
		//---------------------------------------------------------------
		public IActionResult diary()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult elect()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult login()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult my()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult register()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult top()
		{
			return View();
		}
		//---------------------------------------------------------------
		public IActionResult wr()
		{
			return View();
		}
	}
}

exchaD_win10/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using exchaD.Data;

namespace exchaD.Controllers
{
	//登録処理を担う
	public class RegisterController : Controller
    {
		//メンバ
		private readonly ExchaDContext5 context;

		//コンストラクタ
		public RegisterController(ExchaDContext5 c)
		{
			context = c;
		}

		//デフォルトのアクション
		public IActionResult Index()
		{
			return Redirect("/Pages/my/");
		}

		//日記の作成
		[HttpPost]
		[AutoValidateAntiforgeryToken]
//		public async Task<IActionResult> Index([Bind("Id, pass, note, pub")] Diary 
		public async Task<IActionResult> Index(string Id, string pass, string note, PUBLICITY pub)
		{
			//有効か
			if (ModelState.IsValid)
			{
				Diary diary = new Diary(Id, pass, note, DateTime.Now, pub, EXCHA.disable, WRITA.able, DateTime.Now, null);

				context.diaries.Add(diary);	//SQL文の予約
				await context.SaveChangesAsync();	//SQL文の実行
				return View("~/Views/Pages/login.cshtml");
			}//無効のとき
			else
			{
				return View("~/Views/Pages/register.cshtml");
			}
		}
	}
}

exchaD_win10/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using exchaD.Data;

namespace exchaD.Controllers
{
	//日記の設定を変更する
    public class SettingsController : Controller
    {
		//メンバ
		private readonly ExchaDContext5 _context;

		//コンストラクタ
		public SettingsController(ExchaDContext5 context)
		{
			_context = context;
		}

	}
}

exchaD_win10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

exchaD_win10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - exchaD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pages" asp-action="Index" style="font-weight:bold;">交換日記</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pages" asp-action="Index">ホーム</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pages" asp-action="login">ログイン</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pages" asp-action="my">マイページ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Pages" asp-action="diaries">日記一覧</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - exchaD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>